POST http://localhost:8000/users HTTP/1.1
content-Type: "application/json"

{
  "name": "Rodrigo Thenophlo",
  "email": "teste@teste.com",
  "password": "123123"
}

###

POST http://localhost:8000/users/generate_token HTTP/1.1
content-Type: "application/json"

{
  "email": "teste@teste.com",
  "password": "123123"
}